### ISSUE TITLE
CI widget failure breaks dashboard

### ISSUE THREAD

**Issue by antony** [vudash/vudash#53]
```
Error: HTTP client error 404
    at CircleCIResponse.clientError (/home/ant/Projects/strading-dashboard/node_modules/circleci/dist/circleci-response.js:16:16)
    at /home/ant/Projects/strading-dashboard/node_modules/circleci/dist/circleci-request.js:109:43
    at Request._callback (/home/ant/Projects/strading-dashboard/node_modules/circleci/dist/circleci-request.js:95:48)
    at Request.self.callback (/home/ant/Projects/strading-dashboard/node_modules/request/request.js:188:22)
    at Request.emit (events.js:160:13)
    at Request.<anonymous> (/home/ant/Projects/strading-dashboard/node_modules/request/request.js:1171:10)
    at Request.emit (events.js:160:13)
    at IncomingMessage.<anonymous> (/home/ant/Projects/strading-dashboard/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:255:19)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

**Comment by antony** [comment]
My bad - it does not - just bad config.
