### ISSUE TITLE
Error updating datasource <name-of-datasource> Too many open files

### ISSUE THREAD

**Issue by alex-voigt** [vudash/vudash#58]
We have a dashboard with about 10 datasource using the datasource-rest module.

They are all defined like that:
```
{
    "datasource-version-latest": {
        "module": "@vudash/datasource-rest",
        "schedule": 10000,
        "options": {
            "url": "https://some.url.to/file.json",
            "method": "get",
            "headers": {
                "Cookie": "some-key=value"
            }
        }
    }
}
```

For the first hours it works fine but then we always get a message like that:
```
Error updating datasource datasource-version-latest Too many open files
Error
    at new lQ.ErrnoError.lQ.ErrnoError (/dashboard/node_modules/jq-web/jq.min.js:5:11456)
    at Object.nextfd (/dashboard/node_modules/jq-web/jq.min.js:4:29016)
    at Object.createStream (/dashboard/node_modules/jq-web/jq.min.js:4:29527)
    at Object.open (/dashboard/node_modules/jq-web/jq.min.js:5:5784)
    at iB (/dashboard/node_modules/jq-web/jq.min.js:1:31192)
    at gB (/dashboard/node_modules/jq-web/jq.min.js:1:31413)
    at JqTransformer.transform (/dashboard/node_modules/@vudash/transformer-jq/transformer.js:11:12)
    at transformers.reduce (/dashboard/node_modules/vudash/src/modules/widget-datasource-binding/widget-datasource-binding.js:7:17)
    at Array.reduce (&lt;anonymous&gt;)
    at transform (/dashboard/node_modules/vudash/src/modules/widget-datasource-binding/widget-datasource-binding.js:6:23)
    at DatasourceEmitter.datasource.emitter.on.value (/dashboard/node_modules/vudash/src/modules/widget-datasource-binding/widget-datasource-binding.js:15:43)
    at DatasourceEmitter.emit (events.js:180:13)
    at DatasourceEmitter.emit (domain.js:439:23)
    at datasource.fetch.then.data (/dashboard/node_modules/vudash/src/modules/datasource-binder/datasource-binder.js:13:15)
    at &lt;anonymous&gt;
    at process._tickCallback (internal/process/next_tick.js:118:7)
```
The values are not updated anymore. The widgets look like this:

```
{
    "position": {
        "x": 3,
        "y": 4,
        "w": 1,
        "h": 2
    },
    "widget": "vudash-widget-statistic",
    "options": {
        "description": "",
        "colour": "transparent"
    },
    "datasource": "datasource-version-latest",
    "transformations": [
        {
            "transformer": "@vudash/transformer-jq",
            "options": {
                "value": ".version"
            }
        }
    ]
}
```

But the normal widget-time module for example still keeps ticking. We are using latest versions of all vudash stuff.

**Comment by antony** [comment]
Hi @alex-voigt 

This sounds like either you have an extremely low number for 'file descriptors' in your OS, which seems unlikely unless the box is running a load of other stuff.

The more possible explanation is that the JQ command is not exiting, and instead we are opening a new instance for each transformation.

This might be my bug, or it might be an upstream bug in node-jq.

I'll look into it tonight and provide a fix!

**Comment by antony** [comment]
Btw for this use case, whilst i am looking into the issue, you can use the 'transformer-map' transformer which hopefully won't have this problem:

```
transformations": [
        {
            "transformer": "@vudash/transformer-map",
            "options": {
                "value": "version"
            }
        }
    ]
```

**Comment by alex-voigt** [comment]
Thanks! I will give it a try and let you know

**Comment by antony** [comment]
Cool.

A useful command to help me understand what you're facing are:
```bash
$ sysctl fs.file-nr
fs.file-nr = 24672	0	765578
```
The command will give you your machine config. It would be interesting to see how your limits (3rd column) are set. On my Ubuntu desktop machine (with a lot of things running), and running a jq enabled widget, I've got plenty of wiggle room.

**Comment by antony** [comment]
Boom. Recreated it!

```
Error updating datasource datasource-version-latest Too many open files
Error
    at new lQ.ErrnoError.lQ.ErrnoError (/home/ant/Projects/vu-perf/node_modules/jq-web/jq.min.js:5:11456)
    at Object.nextfd (/home/ant/Projects/vu-perf/node_modules/jq-web/jq.min.js:4:29016)
    at Object.createStream (/home/ant/Projects/vu-perf/node_modules/jq-web/jq.min.js:4:29527)
    at Object.open (/home/ant/Projects/vu-perf/node_modules/jq-web/jq.min.js:5:5784)
    at iB (/home/ant/Projects/vu-perf/node_modules/jq-web/jq.min.js:1:31192)
    at gB (/home/ant/Projects/vu-perf/node_modules/jq-web/jq.min.js:1:31413)
    at JqTransformer.transform (/home/ant/Projects/vu-perf/node_modules/@vudash/transformer-jq/transformer.js:11:12)
    at transformers.reduce (/home/ant/Projects/vu-perf/node_modules/vudash/src/modules/widget-datasource-binding/widget-datasource-binding.js:7:17)
    at Array.reduce (<anonymous>)
    at transform (/home/ant/Projects/vu-perf/node_modules/vudash/src/modules/widget-datasource-binding/widget-datasource-binding.js:6:23)
    at DatasourceEmitter.datasource.emitter.on.value (/home/ant/Projects/vu-perf/node_modules/vudash/src/modules/widget-datasource-binding/widget-datasource-binding.js:15:43)
    at DatasourceEmitter.emit (events.js:160:13)
    at datasource.fetch.then.data (/home/ant/Projects/vu-perf/node_modules/vudash/src/modules/datasource-binder/datasource-binder.js:13:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

**Comment by alex-voigt** [comment]
The configuration is:
sysctl fs.file-nr
fs.file-nr = 4480       0       764170

But using the transformer-map works since yesterday without any problems.

**Comment by antony** [comment]
Great!

I'll close this for now, because I think the old JQ implementation had a leak. I've replaced it with a new library now which doesn't seem (in my tests) to leak.
