### ISSUE TITLE
Problem with the loading modules.

### ISSUE THREAD

**Issue by ne0c0de** [vudash/vudash#64]
I have 2 different environments. 1 is Ubuntu 14.04 2 is Mac 

First i tried with ubuntu.

Installed vudash
create sample dashboard and it works.
I changed default dashboard with this:

```
{
  "name": "Happy",
  "layout": {
    "columns": 5,
    "rows": 4
  },
  "datasources": {
    "datasource-exchange-rates": { 
      "module": "@vudash/datasource-rest",
      "schedule": 30000,
      "options": {
        "url": "https://blockchain.info/ticker",
        "method": "get",
        "graph": "USD.last" 
      }
    }
  },
  "widgets": [
    {
      "position": {
        "x": 1,
        "y": 0,
        "w": 3,
        "h": 1
      },
      "widget": "vudash-widget-statistic",
      "datasource": "datasource-exchange-rates",
      "history": 100
    }
  ]
}
```

And got this error:

`Module @vudash/datasource-rest could not be resolved as an NPM module or a local module`

I also tried to start vudash with NODE_PATH=. vudash

but it didn't resolve my problem.

Than i decided to run it on Mac

Installed vudash. create a default dashboard and start vudash

And i got this error even with the default dashboard:

`Module vudash-widget-time could not be resolved as an NPM module or a local module`

Is there a problem with the module installer?

**Comment by ne0c0de** [comment]
I noticed that the problem is starting with this command is not good for vudash: `NODE_PATH=. vudash`
So I tried `npm start` and default dashboard worked on Mac too
Then i tried my custom dashboard and it's failed gain because of same error happened on Ubuntu.

Then i executed this: `npm install --save @vudash/datasource-rest`

And the error changed to `Module vudash-widget-statistic could not be resolved as an NPM module or a local module`

After that I executed this: `npm install vudash-widget-statistic` and voile it's worked finally.

My current problem is trying to understand how to  get a specific node value from the REST API.

For instance: I tried with Bitfinex API which the URL is: https://api.bitfinex.com/v1/pubticker/btcusd

As you can see in the master node of the response there's "last_price" property which i want to show on my dashboard.

My current dashboard is look like this:

```
{
  "name": "Happy",
  "layout": {
    "columns": 5,
    "rows": 4
  },
  "datasources": {
    "datasource-exchange-rates": { 
      "module": "@vudash/datasource-rest",
      "schedule": 30000,
      "options": {
        "url": "https://api.bitfinex.com/v1/pubticker/btcusd",
        "method": "get",
        "graph": "last_price" 
      }
    }
  },
  "widgets": [
    {
      "position": {
        "x": 1,
        "y": 0,
        "w": 3,
        "h": 1
      },
      "widget": "vudash-widget-statistic",
      "datasource": "datasource-exchange-rates",
      "history": 100
    }
  ]
}
```

Bu currently it's showing `[Object object]`

What am I doing wrong?

**Comment by ne0c0de** [comment]
I resolved this too by modifying the script like this:

```
{
  "name": "Happy",
  "layout": {
    "columns": 5,
    "rows": 4
  },
  "datasources": {
    "datasource-exchange-rates": { 
      "module": "@vudash/datasource-rest",
      "schedule": 5000,
      "options": {
        "url": "https://api.bitfinex.com/v1/pubticker/btcusd",
        "method": "get"
      }
    }
  },
  "widgets": [
    {
      "position": {
        "x": 1,
        "y": 0,
        "w": 1,
        "h": 1
      },
      "widget": "vudash-widget-statistic",
      "datasource": "datasource-exchange-rates",
      "history": 100,
      "transformations": [
        {
          "transformer": "@vudash/transformer-map",
          "options": {
            "value": "last_price"
          }
        }
      ],
      "options": {
        "description": " ",
        "format": "$%.2f",
        "historyView": "ticker"
      }
    }
  ]
}
```
Also needed to install transformer-map module with this command: `npm install --save @vudash/transformer-map`

Currently everything is fine.

I loved to work self service 👯‍♂️

**Comment by antony** [comment]
Hi!

Apologies, I hadn't noticed this issue being raised!

I will check into this, as my intention was that the application would work out of the box without extra additional dependencies!

Thanks for working this out :dancing_women:

**Comment by torarnv** [comment]
Seeing the same problem. `vudash` results in:

````
Error: Module vudash-widget-time could not be resolved as an NPM module or a local module
    at throwNotFound (/Users/torarne/.npm-packages/lib/node_modules/vudash/src/resolver/resolver.js:20:9)
    at find.method (/Users/torarne/.npm-packages/lib/node_modules/vudash/src/resolver/resolver.js:29:12)
    at Array.find (<anonymous>)
    at Object.discover (/Users/torarne/.npm-packages/lib/node_modules/vudash/src/resolver/resolver.js:28:5)
    at findPackageRoot (/Users/torarne/.npm-packages/lib/node_modules/vudash/src/widget/loader/index.js:23:37)
    at readPackage (/Users/torarne/.npm-packages/lib/node_modules/vudash/src/widget/loader/index.js:32:23)
    at Object.exports.load (/Users/torarne/.npm-packages/lib/node_modules/vudash/src/widget/loader/index.js:56:10)
    at Widget.register (/Users/torarne/.npm-packages/lib/node_modules/vudash/src/widget/index.js:23:52)
    at widgets.reduce (/Users/torarne/.npm-packages/lib/node_modules/vudash/src/widget-binder/widget-binder.js:31:12)
    at Array.reduce (<anonymous>)
    at Object.exports.load (/Users/torarne/.npm-packages/lib/node_modules/vudash/src/widget-binder/widget-binder.js:17:18)
    at Dashboard.loadWidgets (/Users/torarne/.npm-packages/lib/node_modules/vudash/src/dashboard/dashboard.js:58:46)
    at add (/Users/torarne/.npm-packages/lib/node_modules/vudash/src/dashboard/loader/loader.js:22:13)
    at load (/Users/torarne/.npm-packages/lib/node_modules/vudash/src/dashboard/loader/loader.js:16:10)
    at Object.find (/Users/torarne/.npm-packages/lib/node_modules/vudash/src/dashboard/loader/loader.js:29:25)
    at exports.handler (/Users/torarne/.npm-packages/lib/node_modules/vudash/src/plugins/ui/handlers/dashboard/index.js:26:39)
````

` npm start` works

**Comment by antony** [comment]
Thanks - I will look at this as soon as I have the time (possibly late this week)

**Comment by antony** [comment]
Strange, the install scripts do request that vudash-widget-time is installed.

I'll need to look into this further.
