### ISSUE TITLE
Can't install on Node 12

### ISSUE THREAD

**Issue by chonnimitS2** [vudash/vudash#83]
I can't install from `npm install -g vudash`

```bash
/usr/local/bin/vudash -> /usr/local/lib/node_modules/vudash/bin/vudash.js

> weak@1.0.1 install /usr/local/lib/node_modules/vudash/node_modules/weak
> node-gyp rebuild

make: Entering directory '/usr/local/lib/node_modules/vudash/node_modules/weak/build'
  CXX(target) Release/obj.target/weakref/src/weakref.o
../src/weakref.cc:147:25: error: too few arguments to function call, expected 4, have 3; did you mean 'Nan::Call'?
  globalCallbackDirect->Call(Nan::GetCurrentContext()->Global(), 1, argv);
                        ^~~~
                        Nan::Call
../../nan/nan_maybe_43_inl.h:345:30: note: 'Nan::Call' declared here
inline MaybeLocal<v8::Value> Call(
                             ^
../src/weakref.cc:168:75: error: too few arguments to function call, single argument 'context' was not specified
  Local<Object> proxy = Nan::New<ObjectTemplate>(proxyClass)->NewInstance();
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/siamsquared/Library/Caches/node-gyp/12.4.0/include/node/v8.h:6244:3: note: 'NewInstance' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(Local<Context> context);
  ^
/Users/siamsquared/Library/Caches/node-gyp/12.4.0/include/node/v8config.h:347:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/weakref.cc:223:55: error: no member named 'IsNearDeath' in 'Nan::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >'
  Local<Boolean> rtn = Nan::New<Boolean>(cont->target.IsNearDeath());
                                         ~~~~~~~~~~~~ ^
3 errors generated.
make: *** [weakref.target.mk:129: Release/obj.target/weakref/src/weakref.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/vudash/node_modules/weak/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/vudash/node_modules/weak
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: weak@1.0.1 (node_modules/vudash/node_modules/weak):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: weak@1.0.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ vudash@9.9.0

```

I think problem from this issue from weak https://github.com/TooTallNate/node-weak/issues/99

**Comment by antony** [comment]
Hey - thanks for the bug report. I've not seen this error myself, it looks like a native module. I'll have to have a look when I get a minute.

For reference, I've not tried this with Node 12. I developed it and use it on Node 8.
